import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import TopNav from "./components/TopNav";
import Footer from "./components/Footer";
import Head from "next/head";
import "../lib/fontawsome"

import TopNav from "./components/TopNav";
import HeaderLinks from "./components/HeaderLinks";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link
              rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
              integrity="sha512-..."
            />
        <style>
        @import url(&quot https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap &quot);
        </style>
      </Head>
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeaderLinks/>
        <TopNav/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
